#!/usr/bin/env python
import os
import subprocess
import sys

_DIR = os.path.dirname(os.path.abspath(__file__))
_ZSHRC = os.path.expanduser('~/.zshrc')
_TMUX = os.path.expanduser('~/.tmux.conf')
_VIM = os.path.expanduser('~/.vimrc')
_VIM_LOCAL = os.path.expanduser('~/.vimrc.local')
_FASD = os.path.expanduser('~/bin/fasd')
_GITCONFIG = os.path.expanduser('~/.gitconfig')
_GLOBAL_GITIGNORE = os.path.expanduser('~/.gitignore_global')


def _read(filename):
    with open(filename, 'r') as f:
        return f.read()


def _write(filename, content):
    with open(filename, 'w') as f:
        f.write(content)


def main():
    subprocess.check_call('git submodule update --init --recursive', cwd=_DIR, shell=True)

    if not os.path.isfile(_ZSHRC):
        print("Setting ZSHRC")
        template = _read(os.path.join(_DIR, 'oh-my-zsh', 'templates', 'zshrc.zsh-template'))
        template = template.replace('export ZSH=$HOME/.oh-my-zsh', 'export ZSH="{0}"'.format(os.path.join(_DIR, 'oh-my-zsh')))
        _write(_ZSHRC, template)

    if not os.path.isfile(_TMUX):
        print("Setting TMUX config")
        os.symlink(os.path.join(_DIR, 'tmux-config', '.tmux.conf'), _TMUX)

    if not os.path.isfile(_VIM_LOCAL):
        print("Setting VIM local file")
        os.symlink(os.path.join(_DIR, '.vimrc.local'), _VIM_LOCAL)

    if not os.path.isfile(_VIM):
        subprocess.check_call('curl http://j.mp/spf13-vim3 -L -o - | sh', shell=True)

    if not os.path.isfile(_FASD):
        print("Setting FASD")
        os.symlink(os.path.join(_DIR, 'fasd', 'fasd'), _FASD)

    if not os.path.isfile(_GLOBAL_GITIGNORE):
        print("Setting global git ignore")
        os.symlink(os.path.join(_DIR, 'gitignore_global'), _GLOBAL_GITIGNORE)

    subprocess.check_call(['git', 'config', '--global', 'include.path', os.path.join(_DIR, 'gitconfig')])


if __name__ == "__main__":
    sys.exit(main())
