(defun darwish/python-pytest-parametrize (&optional values-list)
  (interactive)
  (let ((symbol (current-word)))
    (back-to-indentation)
    (forward-line -1)
    (move-end-of-line nil)
    (newline-and-indent)
    (beginning-of-line)
    (let ((beg (point)))
      (forward-line 1)
      (forward-char -1)
      (delete-region beg (point)))
    (insert (format "@pytest.mark.parametrize('%s', [%s])" symbol (if values-list values-list "")))
    (backward-char 2)

    ))

(defun darwish/python-pytest-parametrize-boolean ()
  (interactive)
  (save-excursion
    (darwish/python-pytest-parametrize "True, False")))
